@ECHO Off
	ECHO DANG XOA BUILD CACHE
	DEL Build\*.pdb
	ECHO DANG XOA SERVER BUILD
	ECHO Y | RMDIR /S VFLauncher\obj
	ECHO Y | RMDIR /S VFLauncher\bin
	ECHO Y | RMDIR /S VFPlay\obj
	ECHO Y | RMDIR /S VFPlay\bin
	ECHO DANG XOA LIBRARY BUILD
	
	ECHO DA XOA THANH CONG...! NHAN PHIM BAT KY DE THOAT...!
	PAUSE
EXIT